### ISSUE TITLE
now playing view not working

### ISSUE THREAD

**Issue by qDave17** [yattee/yattee#19]
using beta for ios 14 and 
![CE789B4D-C78B-498A-A325-4CC34F6F2EF3](https://user-images.githubusercontent.com/78225290/144124188-8228755d-3f7b-4073-a0f9-77dccc2392bc.png)
just stays like this, can't watch the video

**Comment by arekf** [comment]
Thanks for reporting, should be fixed in [1.2-beta.2](https://github.com/yattee/yattee/releases/tag/v1.2-beta.2) build.

**Comment by Jenni32222** [comment]
Using 1.2-beta.3, this issue is back. Video's will not play and will crash the app.

**Comment by arekf** [comment]
@Jenni32222 please include details: system version and device, and crash log if possible

**Comment by Jenni32222** [comment]
iPhone XS Max running iOS 15.1
Unfortunately no crash log
